Telematics/Models/ReportViewModel.cs
using Microsoft.PowerBI.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.PowerBI.Api.V1.Models;

namespace Telematics.Models
{
    public class ReportViewModel
    {
        public Report Report { get; set; }

        public string AccessToken { get; set; }
    }
}

Telematics/Models/ReportsViewModel.cs
using System.Collections.Generic;
using Microsoft.PowerBI.Api.V1.Models;

namespace Telematics.Models
{
    public class ReportsViewModel
    {
        public List<Report> Reports { get; set; }
    }

    public class GPSViewModel
    {
        public IList<VehicleGPS> gps_location_list { get; set; }
    }
}

Telematics/Controllers/DashboardController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Services;
using Microsoft.PowerBI.Api.V1;
using Microsoft.PowerBI.Security;
using Microsoft.Rest;
using Telematics.Models;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using System.Net.Mail;
using System.Net;

namespace Telematics.Controllers
{
    public class DashboardController : Controller
    {
        private readonly string workspaceCollection;
        private readonly string workspaceId;
        private readonly string accessKey;
        private readonly string apiUrl;
        private string currentworkspaceid;

        public DashboardController()
        {
            this.workspaceCollection = ConfigurationManager.AppSettings["powerbi:WorkspaceCollection"];
            this.workspaceId = ConfigurationManager.AppSettings["powerbi:WorkspaceId"];
            this.accessKey = ConfigurationManager.AppSettings["powerbi:AccessKey"];
            this.apiUrl = ConfigurationManager.AppSettings["powerbi:ApiUrl"];
        }

        [WebMethod]
        public JsonResult GetAllItems()
        {
            var gps_update_query = new List<Logs>();
            using (var db = new ApplicationDbContext())
            {
                gps_update_query = (from g in db.Logs
                                    select g).ToList();
            }
            return Json(new { Data = gps_update_query }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Scoring()
        {
            var trip_list = new List<ScoreList>();
            var grade_a = 0;
            var grade_b = 0;
            var grade_c = 0;
            using (var db = new ApplicationDbContext())
            {
                var current_user = (from u in db.Users
                                    where u.UserName == User.Identity.Name
                                    select u).FirstOrDefault();

                trip_list = (from t in db.Trips
                             group t by new { t.driver } into new_t
                             select new ScoreList
                             {
                                 driver = new_t.Key.driver,
                                 score = new_t.Sum(t => t.score),
                                 count = new_t.Count()
                             }).ToList();
                foreach(ScoreList sl in trip_list)
                {
                    if(sl.score > 75)
                    {
                        grade_a++;
                    }
                    else if(sl.score > 50)
                    {
                        grade_b++;
                    }
                    else
                    {
                        grade_c++;
                    }
                }
            }
            var model = new ScoreViewModel()
            {
                scores = trip_list,
                gradeA = grade_a,
                gradeB = grade_b,
                gradeC = grade_c
            };

            return View(model);
        }

        public async Task<ActionResult> Details(string driver)
        {
            var driver_details = new List<Trips>();
            using (var db = new ApplicationDbContext())
            {
                driver_details = (from t in db.Trips
                                  orderby t.timeStamp descending
                                  where t.driver == driver
                                  select t).ToList();
            }
            var model = new DetailsViewModel()
            {
                trips = driver_details,
                driver = driver
            };
            return View(model);
        }

        public async Task<ActionResult> Track()
        {
            var driverLatestLocation = new List<Drivers_GPSData>();
            using (var db = new ApplicationDbContext())
            {
                var unique_driverids = (from d in db.Drivers_GPSData
                                        select d.driverid).Distinct().ToList();

                driverLatestLocation = (from d in unique_driverids
                                            from g in db.Drivers_GPSData.Where(dg => dg.driverid == d)
                                                                        .OrderByDescending(dg => dg.timeStamp)
                                                                        .Take(1)
                                                                        .DefaultIfEmpty()
                                            select g).ToList();
                

            };
            var model = new TrackViewModel()
            {
                drivergps = driverLatestLocation.ToList()
            };
            return View(model);
        }

        public async Task<ActionResult> Index()
        {
            var vehicle_gps_list = new List<VehicleGPS>();
            using (var db = new ApplicationDbContext())
            {
                var current_user = (from u in db.Users
                                where u.UserName == User.Identity.Name
                                select u).FirstOrDefault();                

                vehicle_gps_list = (from g in db.VehicleStatus
                                    join o in db.OBD on g.vehicle_id equals o.device_id
                                    join v in db.Vehicle on g.vehicle_id equals v.device_no
                                    where o.company == current_user.Company
                                    select new VehicleGPS { vVehicleStatus = g, vOBD = o, vehicle = v }).ToList();
            }
            var model = new GPSViewModel()
            {
                gps_location_list = vehicle_gps_list.ToList()
            };

            return View(model);
        }

        [ChildActionOnly]
        public ActionResult Reports()
        {
            using (var db = new ApplicationDbContext())
            {
                var current_company = (from c in db.Companie
                                       join u in db.Users on c.name equals u.Company
                                       where u.UserName == User.Identity.Name
                                       select c).FirstOrDefault();
                currentworkspaceid = current_company.reportID;
            }
            using (var client = this.CreatePowerBIClient())
            {
                var reportsResponse = client.Reports.GetReports(this.workspaceCollection, currentworkspaceid);

                var viewModel = new ReportsViewModel
                {
                    Reports = reportsResponse.Value.ToList()
                };

                return PartialView(viewModel);
            }
        }

        public async Task<ActionResult> Report(string reportId)
        {
            using (var db = new ApplicationDbContext())
            {
                var current_company = (from c in db.Companie
                                       join u in db.Users on c.name equals u.Company
                                       where u.UserName == User.Identity.Name
                                       select c).FirstOrDefault();
                currentworkspaceid = current_company.reportID;
            }
            using (var client = this.CreatePowerBIClient())
            {
                var reportsResponse = await client.Reports.GetReportsAsync(this.workspaceCollection, currentworkspaceid);
                var report = reportsResponse.Value.FirstOrDefault(r => r.Id == reportId);
                var embedToken = PowerBIToken.CreateReportEmbedToken(this.workspaceCollection, currentworkspaceid, report.Id);

                var viewModel = new ReportViewModel
                {
                    Report = report,
                    AccessToken = embedToken.Generate(this.accessKey)
                };

                return View(viewModel);
            }
        }

        private IPowerBIClient CreatePowerBIClient()
        {
            var credentials = new TokenCredentials(accessKey, "AppKey");
            var client = new PowerBIClient(credentials)
            {
                BaseUri = new Uri(apiUrl)
            };

            return client;
        }

        [WebMethod]
        public JsonResult GetGPSUpdates()
        {


            //try
            //{
            //    //SmtpClient client = new SmtpClient();
            //    //client.Port = 587;
            //    //client.DeliveryMethod = SmtpDeliveryMethod.Network;
            //    //client.UseDefaultCredentials = false;
            //    //client.Host = "smtp.gmail.com";
            //    //client.EnableSsl = true;
            //    //client.UseDefaultCredentials = false;
            //    //client.Credentials = new System.Net.NetworkCredential("itadmin@digital-safety.sg", "Atarash13");

            //    //MailMessage mail = new MailMessage("itadmin@digital-safety.sg", "andrewwongcr@hotmail.com");
            //    //mail.Subject = "This is test mail";
            //    //mail.Body = "this is test mail body";

            //    //client.Send(mail);

            //    string username = "atarashib@gmail.com"; // "ali@digital-safety.sg";
            //    string password = "Atarash13";
            //    string smtpserver = "smtp.gmail.com";

            //    SmtpClient smtpClient = new SmtpClient();
            //    NetworkCredential basicCredential = new NetworkCredential(username, password);
            //    MailMessage message = new MailMessage();
            //    MailAddress fromAddress = new MailAddress(username);

            //    // setup up the host, increase the timeout to 5 minutes
            //    smtpClient.Host = smtpserver;
            //    smtpClient.UseDefaultCredentials = false;
            //    smtpClient.Credentials = basicCredential;
            //    smtpClient.Timeout = (60 * 5 * 1000);

            //    message.From = fromAddress;

Telematics/Views/Shared/Reports.cshtml
@using Telematics.Models
@model ReportsViewModel
@{
    Layout = null;

    var classNames = "panel panel-default dropdown";

    if (this.Request.Path.IndexOf("Report") > -1)
    {
        classNames += " active";
    }
}

<li class="@classNames">
    <a data-toggle="collapse" href="#reports-nav">
        <span class="icon fa fa-bar-chart"></span><span class="title">Reports</span>
    </a>
    <!-- Dropdown level 1 -->
    <div id="reports-nav" class="panel-collapse collapse">
        <div class="panel-body">
            <ul class="nav navbar-nav">
                @foreach (var report in Model.Reports)
                {
                    var reportClass = Request.QueryString["reportId"] == report.Id ? "active" : "";
                    <li class="@reportClass">
                        @Html.ActionLink(report.Name, "Report", new { reportId = report.Id })
                    </li>
                }
            </ul>
        </div>
    </div>
</li>

Telematics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Drive Safe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="/lib/css/bootstrap.min.css" /><!--https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <link rel="stylesheet" type="text/css" href="/lib/css/font-awesome.min.css" /> <!--http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">-->
    <link rel="stylesheet" type="text/css" href="/lib/css/animate.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/bootstrap-switch.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/checkbox3.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/dataTables.bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/lib/css/select2.min.css">
    <!-- CSS App -->
    <link href="~/Content/powerbi.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/themes/flat-blue.css">
</head>
<body class="flat-blue">
    <div class="app-container">
        <div class="row content-container">
            <nav class="navbar navbar-default navbar-fixed-top navbar-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-expand-toggle">
                            <i class="fa fa-bars icon"></i>
                        </button>
                        @RenderSection("Breadcrumbs", false)
                        <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                            <i class="fa fa-th icon"></i>
                        </button>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                            <i class="fa fa-times icon"></i>
                        </button>
                        <!--<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-comments-o"></i></a>
                            <ul class="dropdown-menu animated fadeInDown">
                                <li class="title">
                                    Notification <span class="badge pull-right">0</span>
                                </li>
                                <li class="message">
                                    No new notification
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown danger">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-star-half-o"></i> 4</a>
                            <ul class="dropdown-menu danger  animated fadeInDown">
                                <li class="title">
                                    Notification <span class="badge pull-right">4</span>
                                </li>
                                <li>
                                    <ul class="list-group notifications">
                                        <a href="#">
                                            <li class="list-group-item">
                                                <span class="badge">1</span> <i class="fa fa-exclamation-circle icon"></i> new registration
                                            </li>
                                        </a>
                                        <a href="#">
                                            <li class="list-group-item">
                                                <span class="badge success">1</span> <i class="fa fa-check icon"></i> new orders
                                            </li>
                                        </a>
                                        <a href="#">
                                            <li class="list-group-item">
                                                <span class="badge danger">2</span> <i class="fa fa-comments icon"></i> customers messages
                                            </li>
                                        </a>
                                        <a href="#">
                                            <li class="list-group-item message">
                                                view all
                                            </li>
                                        </a>
                                    </ul>
                                </li>
                            </ul>
                        </li>-->
                        <li class="dropdown profile">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">@User.Identity.Name<span class="caret"></span></a>
                            <ul class="dropdown-menu animated fadeInDown">
                                <li>
                                    <div class="profile-info">
                                        <h4 class="username">@User.Identity.Name</h4>
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <p>Admin</p>

                                        }
                                        else if (User.IsInRole("Manager"))
                                        {
                                            <p>Manager</p>
                                        }
                                        <div class="btn-group margin-bottom-2x" role="group">
                                            <button type="button" class="btn btn-default"><i class="fa fa-user"></i> Profile</button>
                                            @{
                                                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <button type="submit" class="btn btn-default"><i class="fa fa-sign-out"></i> Logout</button>

                                                }
                                            }
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="side-menu sidebar-inverse">
                <nav class="navbar navbar-default" role="navigation">
                    <div class="side-menu-container">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <div class="icon fa fa-paper-plane"></div>
                                <div class="title">DriveSafe</div>
                            </a>
                            <button type="button" class="navbar-expand-toggle pull-right visible-xs">
                                <i class="fa fa-times icon"></i>
                            </button>
                        </div>
                        <ul class="nav navbar-nav">
                            @{
                                var className = Request.Path == "/" && Request.QueryString.Count == 0 ? "active" : "";
                            }
                            <li class="@className">
                                @if (User.Identity.Name == "davidtan@citrine.sg")
                                {
                                    <a href="/Dashboard/Track">
                                        <span class="icon fa fa-th-large"></span><span class="title">Dashboard</span>
                                    </a>
                                }
                                else
                                {
                                    <a href="/Dashboard/Index">
                                        <span class="icon fa fa-th-large"></span><span class="title">Dashboard</span>
                                    </a>
                                }
                            </li>
                            @if (User.Identity.Name == "davidtan@citrine.sg")
                            {
                                <li class="@className">
                                    <a href="/Dashboard/Scoring">
                                        <span class="icon fa fa-users"></span><span class="title">Drivers Score</span>
                                    </a>
                                </li>
                            }
                            @if (!User.IsInRole("Driver")) {
                                if(User.Identity.Name != "davidtan@citrine.sg")
                                { 
                                <li class="@className">
                                    <a href="/Account/Management">
                                        <span class="icon fa fa-users"></span><span class="title">Account Management</span>
                                    </a>
                                </li>
                                    }
                                }
                            @if (User.Identity.Name != "davidtan@citrine.sg")
                            {
                            <li class="@className">
                                <a href="/Account/Vehicles">
                                    <span class="icon fa fa-car"></span><span class="title">Vehicle Management</span>
                                </a>
                            </li>
                            @*<li class="@className">
                                <a href="/Dashboard/Report?id=4463e7da-1fbe-483e-8aaf-c5b906a48bf7">
                                    <span class="icon fa fa-car"></span><span class="title">Report</span>
                                </a>
                            </li>*@
                            @Html.Action("Reports", "Dashboard") 
                            }
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
            </div>
            <!-- Main Content -->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- <footer class="app-footer">
            <div class="wrapper">
                <span class="pull-right">2.1 <a href="#"><i class="fa fa-long-arrow-up"></i></a></span> © 2015 Copyright.
            </div>
        </footer> -->
    </div>
    <!-- Javascript Libs -->
    <script type="text/javascript" src="/lib/js/jquery.min.js"></script>
    <script type="text/javascript" src="/lib/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/lib/js/Chart.min.js"></script>
    <script type="text/javascript" src="/lib/js/bootstrap-switch.min.js"></script>
    <script type="text/javascript" src="/lib/js/jquery.matchHeight-min.js"></script>
    <script type="text/javascript" src="/lib/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/lib/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="/lib/js/select2.full.min.js"></script>
    <script type="text/javascript" src="/lib/js/ace/ace.js"></script>
    <script type="text/javascript" src="/lib/js/ace/mode-html.js"></script>
    <script type="text/javascript" src="/lib/js/ace/theme-github.js"></script>
    <!-- Javascript -->
    <script type="text/javascript" src="/js/app.js"></script>
    <script src="~/Scripts/powerbi.js"></script>
    @RenderSection("PageScripts", false)
</body>
</html>